name: timetable
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: 1.0.2
  equatable: 2.0.3
  flutter_bloc: 8.0.0
  json_serializable: 6.1.3
  get_it:
  auto_route:
  collection: 1.15.0
  google_fonts: 2.1.1
  intl:
  flutter_sticky_header:
  flutter_slidable: 1.2.0
  modal_bottom_sheet:
  copy_with_extension_gen: 4.0.0
  pin_code_fields: ^7.3.0
  weekday_selector: ^1.0.0
  flutter_signin_button: ^2.0.0

  # Firebase
  firebase_core: 1.10.6
  firebase_auth: 3.3.4
  cloud_firestore: 3.1.5
  google_sign_in: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: 1.0.0
  json_annotation: 4.4.0
  build_runner: 2.1.7
  auto_route_generator:

flutter:
  uses-material-design: true

  assets:
    - assets/json/
